// INPUT RECORDS
export const FETCH_INPUT_REPORTS_PENDING = 'FETCH_INPUT_REPORTS_PENDING';
export const FETCH_INPUT_REPORTS_SUCCESS = 'FETCH_INPUT_REPORTS_SUCCESS';
export const FETCH_INPUT_REPORTS_FAILURE = 'FETCH_INPUT_REPORTS_FAILURE';

// INPUT RECORD MATCHES
export const FETCH_MATCHES_PENDING = 'FETCH_MATCHES_PENDING';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_FAILURE = 'FETCH_MATCHES_FAILURE';

// SELECT MATCH
export const SELECT_MATCH_PENDING = 'SELECT_MATCH_PENDING';
export const SELECT_MATCH_SUCCESS = 'SELECT_MATCH_SUCCESS';
export const SELECT_MATCH_FAILURE = 'SELECT_MATCH_FAILURE';
