# Generated by Django 2.1.3 on 2018-11-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sound_recordings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputreportmatch',
            old_name='sound_recordings',
            new_name='sound_recording',
        ),
    ]
