# Generated by Django 2.1.3 on 2018-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_recordings', '0002_auto_20181109_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputreport',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inputreport',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inputreport',
            name='isrc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inputreport',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecording',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecording',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecording',
            name='isrc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='soundrecording',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
