export const FETCH_INPUT_REPORTS_PENDING = 'FETCH_INPUT_REPORTS_PENDING'
export const FETCH_INPUT_REPORTS_SUCCESS = 'FETCH_INPUT_REPORTS_SUCCESS'
export const FETCH_INPUT_REPORTS_FAILURE = 'FETCH_INPUT_REPORTS_FAILURE'